import type { Metadata } from "next"
import Link from "next/link"
import { MarketingLayout } from "@/components/marketing/marketing-layout"
import { AnalyticsLink } from "@/components/analytics-link"

export const metadata: Metadata = { title: "Enterprise UI Consulting", description: "Selected SAPUI5, Fiori, SAP BTP application, Salesforce UI, documentation, and modern web project support from Bryan Cash.", alternates: { canonical: "/consulting" } }

const services = [
  ["SAPUI5 & Fiori application delivery", "Focused frontend development, modernization, troubleshooting, and usability improvements for enterprise SAP applications."],
  ["SAP BTP application support", "Frontend and application-layer support for BTP solutions, including CAP-backed experiences, API consumption, and Work Zone-connected applications."],
  ["Salesforce Experience Cloud & enterprise UI", "Partner-facing interface implementation and practical UI improvements for Salesforce experiences."],
  ["Technical documentation & solution support", "Clear specifications, implementation guidance, decision records, testing support, and technical communication for delivery teams."],
  ["React, Next.js & small-business websites", "Selected web applications and business sites when the project has a clear scope, audience, and outcome."],
]

export default function ConsultingPage() { return <MarketingLayout><section className="px-5 py-20 sm:px-6"><div className="mx-auto max-w-6xl"><p className="text-sm font-semibold text-brand-primary">SELECTED CONSULTING AVAILABILITY</p><h1 className="mt-3 max-w-4xl text-4xl font-bold sm:text-6xl">Practical enterprise UI support with a clear scope and a dependable handoff.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">I take on selected engagements where my hands-on SAPUI5, Fiori, BTP application, Salesforce UI, documentation, or modern frontend experience is a direct fit. Each engagement starts with the problem and deliverable—not a catalog of every technology I have encountered.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><AnalyticsLink href="mailto:hello@cashbryan.com?subject=Consulting%20inquiry" event="consulting_inquiry_started" className="rounded-md bg-brand-primary px-5 py-3 text-center font-semibold text-black">Start a project conversation</AnalyticsLink><Link href="/projects" className="rounded-md border border-border px-5 py-3 text-center font-semibold">Review work</Link></div><section className="mt-20"><h2 className="text-3xl font-bold">Where I can help</h2><div className="mt-7 grid gap-5 md:grid-cols-2">{services.map(([title, text]) => <article key={title} className="rounded-xl border border-border/60 bg-card/30 p-6"><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-muted-foreground">{text}</p></article>)}</div></section><section id="process" className="mt-20 rounded-2xl bg-surface-canvas p-7 md:p-10"><p className="text-sm font-semibold text-brand-primary">PROCESS</p><h2 className="mt-3 text-3xl font-bold">Brief → fit check → scoped recommendation → delivery → handoff</h2><p className="mt-4 max-w-3xl leading-7 text-muted-foreground">Send the problem, current stack, desired outcome, constraints, and timing. I will respond with fit, open questions, and a sensible next step. If the work is better suited to a specialist outside my verified delivery strengths, I will say so.</p><Link href="/services" className="mt-6 inline-block font-semibold text-brand-primary">Explore detailed services →</Link></section></div></section></MarketingLayout> }
