"use client"

import { track } from "@vercel/analytics"
import { useEffect } from "react"
import type { Proposal } from "@/lib/proposals/types"

export function ProposalTemplate({ proposal }: { proposal: Proposal }) {
  useEffect(() => track("proposal_viewed", { proposal: proposal.slug }), [proposal.slug])
  return <main id="main-content" className="min-h-screen bg-background px-5 py-14"><div className="mx-auto max-w-5xl"><p className="text-sm font-semibold text-brand-primary">PRIVATE PROPOSAL · {proposal.client}</p><h1 className="mt-3 text-4xl font-bold sm:text-6xl">{proposal.project}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground">{proposal.overview}</p><div className="mt-14 grid gap-6 md:grid-cols-2"><section className="rounded-xl border border-border p-6"><h2 className="text-2xl font-semibold">Current problem</h2><p className="mt-3 text-muted-foreground">{proposal.problem}</p></section><section className="rounded-xl border border-brand-primary/30 bg-brand-soft p-6"><h2 className="text-2xl font-semibold">Recommended solution</h2><p className="mt-3 text-muted-foreground">{proposal.solution}</p></section></div><section className="mt-14"><h2 className="text-3xl font-bold">Scope & deliverables</h2><ul className="mt-5 grid gap-3 sm:grid-cols-2">{proposal.deliverables.map(item => <li key={item} className="rounded-lg border border-border/60 p-4">✓ {item}</li>)}</ul></section><section className="mt-14"><h2 className="text-3xl font-bold">Options</h2><div className="mt-6 grid gap-5 md:grid-cols-2">{proposal.packages.map(option => <article key={option.name} className="rounded-xl border border-border p-6"><h3 className="text-xl font-semibold">{option.name}</h3><p className="mt-2 text-2xl font-bold text-brand-primary">{option.price}</p><p className="mt-3 text-muted-foreground">{option.description}</p></article>)}</div></section><section className="mt-14 rounded-2xl bg-surface-canvas p-7"><h2 className="text-2xl font-semibold">Timeline</h2><p className="mt-3 text-muted-foreground">{proposal.timeline}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><a href={`mailto:hello@cashbryan.com?subject=${encodeURIComponent(`Accept proposal: ${proposal.project}`)}`} onClick={() => track("proposal_cta_selected", { proposal: proposal.slug, action: "accept" })} className="rounded-md bg-brand-primary px-5 py-3 text-center font-semibold text-black">Accept / choose an option</a><a href={`mailto:hello@cashbryan.com?subject=${encodeURIComponent(`Changes requested: ${proposal.project}`)}`} onClick={() => track("proposal_cta_selected", { proposal: proposal.slug, action: "changes" })} className="rounded-md border border-border px-5 py-3 text-center font-semibold">Request changes</a></div></section></div></main>
}
