import type { Metadata } from "next"
import Link from "next/link"

export const metadata: Metadata = { title: "Selected Enterprise Projects", description: "Career-focused summaries of Bryan Cash's verified contributions to enterprise SAP, Salesforce, and UI delivery.", alternates: { canonical: "/career/projects" } }

const projects = [
  { title: "Manufacturer reporting portal", href: "/projects/manufacturer-portal", contribution: "Developed enterprise SAPUI5 reporting applications and supported a SAP BTP portal program connecting Build Work Zone, CAP services, Datasphere data, and identity-based access.", shows: "SAPUI5 delivery, BTP application work, enterprise reporting, stakeholder coordination, testing, and production support." },
  { title: "Railroad fuel applications", href: "/projects/fuel-management", contribution: "Built SAPUI5 applications supporting enterprise fuel workflows and translated operational requirements into usable interfaces.", shows: "Hands-on SAPUI5 development, enterprise UX, requirements translation, and delivery ownership." },
  { title: "Salesforce Experience Cloud", href: "/projects/partner-portal", contribution: "Worked as the developer and designer for a partner-facing Experience Cloud implementation surfacing warranty and support workflows.", shows: "Salesforce UI, independent delivery, frontend design, and business workflow understanding." },
  { title: "Developer mentoring and technical enablement", href: "/about", contribution: "Delivered SAPUI5 and CAP training, mentored developers, and created technical demonstrations and documentation for enterprise teams.", shows: "Team leadership, teaching, documentation, and stakeholder communication." },
]

export default function ProjectsPage() { return <><p className="text-sm font-semibold text-brand-primary">SELECTED COMMERCIAL WORK</p><h1 className="mt-3 text-4xl font-bold sm:text-5xl">What I contributed—not just what the program delivered.</h1><p className="mt-5 max-w-3xl text-lg text-muted-foreground">These summaries are written for hiring teams and distinguish Bryan’s responsibilities from broader program outcomes.</p><p className="mt-4 max-w-3xl text-sm text-muted-foreground">Client identities and selected implementation details have been generalized to protect confidentiality.</p><div className="mt-12 space-y-5">{projects.map(p => <article key={p.title} className="rounded-xl border border-border/60 bg-card/30 p-6 md:p-8"><h2 className="text-2xl font-semibold">{p.title}</h2><p className="mt-4 leading-7 text-muted-foreground"><strong className="text-foreground">Contribution:</strong> {p.contribution}</p><p className="mt-3 leading-7 text-muted-foreground"><strong className="text-foreground">Demonstrates:</strong> {p.shows}</p><Link href={p.href} className="mt-5 inline-block font-semibold text-brand-primary hover:underline">Review available case study →</Link></article>)}</div><p className="mt-8 rounded-lg border border-border/60 p-4 text-sm text-muted-foreground">Commercial case studies are NDA-safe summaries. Metrics and organization-wide outcomes should be treated as program context unless Bryan’s individual ownership is explicitly stated.</p></> }
